sudo: false

language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - pytest --cov=./

notifications:
  email: change

after_success:
  - codecov
